spring:
  datasource:
    username: root
    password: sjh9323
    url: jdbc:mysql://localhost:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml   # mapper sql映射文件位置
  global-config:
    db-config:
      id-type: auto  # 自增主键

server:
  port: 7000
