spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-search

  thymeleaf:
    cache: false

  session:
    store-type: redis

  redis:
    host: 172.17.0.1
    port: 6379
    password: sjh9323

server:
  port: 12000